api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths:
            - "%kernel.project_dir%/src/Infrastructure/ApiPlatform/Resources"
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
