framework:
    validation:
        mapping:
            paths:
                - "%kernel.project_dir%/src/Application/Validator"

when@test:
    framework:
        validation:
            not_compromised_password: false
